# Generated by Django 4.0.2 on 2022-02-26 18:08

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='articlemodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('pdate', models.DateField()),
                ('mdate', models.DateField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authe.registermodel')),
            ],
        ),
        migrations.CreateModel(
            name='commments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('cdate', models.DateTimeField(default=datetime.datetime(2022, 2, 26, 18, 8, 10, 194131, tzinfo=utc))),
                ('comname', models.CharField(max_length=50)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.articlemodel')),
            ],
        ),
    ]
